### ISSUE TITLE
Adios build failare when python > 3.7

### ISSUE THREAD

**Issue by Yikun** [openhpc/ohpc#1627]
Encounter error like:
```
 #warning "Using deprecated NumPy API, disable it with " \
  ^~~~~~~
adios.cpp: In function 'PyObject* PyInit_adios()':
adios.cpp:52250:30: error: 'PyTypeObject {aka struct _typeobject}' has no member named 'tp_print'; did you mean 'tp_dict'?
   __pyx_type_5adios_softdict.tp_print = 0;
                              ^~~~~~~~
                              tp_dict
```

[1] https://github.com/ornladios/ADIOS/issues/202
[2] https://github.com/ornladios/ADIOS/issues/216

**Comment by adrianreber** [comment]
I have also seen it when trying to build adios on RHEL 9. Would be good if you find a working fix.

**Comment by Yikun** [comment]
[Here](https://github.com/ornladios/ADIOS/issues/216#issuecomment-1004744955) had a solution, but I'm not sure should we also need do same workaround.

```
            os.remove('adios.cpp')
            os.remove('adios_mpi.cpp')
```

**Comment by adrianreber** [comment]
My idea was to switch to adios2.

**Comment by adrianreber** [comment]
You could try to delete those files and see if they are re-created. They seem like generated code.

**Comment by Yikun** [comment]
```
[  417s] + rm -f adios.cpp adios_mpi.cpp
[  417s] + make CYTHON=y MPI=y python
[  417s] cython --cplus adios_mpi.pyx
[  417s] make: cython: No such file or directory
[  417s] make: *** [Makefile:36: adios_mpi.cpp] Error 127
```

Looks  like not working

**Comment by adrianreber** [comment]
Did you install `cython`?

**Comment by Yikun** [comment]
I just added the `BuildRequires:  %{python_prefix}-Cython%{PROJ_DELIM}`, also not working, looks like `adios_mpi.pyx` requires `adios.cpp adios_mpi.cpp`.


[1] https://build.openeuler.openatom.cn/package/live_build_log/home:huangtianhua:ohpc/adios-gnu12-openmpi4/standard_aarch64/aarch64

**Comment by martin-g** [comment]
According to https://raw.githubusercontent.com/ornladios/ADIOS/master/wrappers/numpy/adios.cpp the problem should happen only for `#if PY_VERSION_HEX < 0x030800B1` (3.8.0 beta1). 
See https://github.com/python/cpython/blob/main/Include/patchlevel.h
openEuler 22.03 uses Python 3.9.9 and Cython 0.29.25, so it should not be a problem there.
https://build.openeuler.openatom.cn/package/live_build_log/home:huangtianhua:ohpc/adios-gnu12-openmpi4/standard_aarch64/aarch64 confirms this: `/usr/lib64/python3.9/site-packages/Cython/Compiler/Main.py:369...`

I will check with @Yikun how to reproduce the initial problem!

**Comment by martin-g** [comment]
I think I've found the problem with the build:

https://github.com/ornladios/ADIOS/releases/tag/v1.13.1 is released at Apr 18, 2018
The fix for Cython 0.29 is made at Oct 2, 2019 with https://github.com/ornladios/ADIOS/commit/327e15919ce7369d556f6bb0d3b79af9066aed39
i.e. only master is buildable, but 1.13.1 (latest release) is broken

**Comment by adrianreber** [comment]
Can this be fixed by backporting a single patch? Still not sure we actually need a fix or if we should just try to use adios2.

**Comment by martin-g** [comment]
I think it can be backported by applying the above commit as a patch (https://github.com/ornladios/ADIOS/commit/327e15919ce7369d556f6bb0d3b79af9066aed39.patch)
Let me try it!

**Comment by martin-g** [comment]
I needed to create a .patch for all commits between v1.13.1 and `master` as of today for wrappers/numpy/adios.cpp and adios_mpi.cpp.
The build passed for https://github.com/openhpc/ohpc/pull/1635 !
I've squashed the commits and now the checks run again!

**Comment by adrianreber** [comment]
This is fixed, right? Closing.

**Comment by martin-g** [comment]
We (openEuler) still have issues with the Python 2 files in ADIOS1.
This is the reason I opened https://github.com/openhpc/ohpc/issues/1639
